<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/Day43.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 43

Load X_train.csv and X_test.csv files respectively to DataFrame named X_train and X_test.

Then use the StandardScaler class from the scikit-learn package to standardize the data (fit the scaler on the X_train).

In response, print the first five rows of X_train and X_test to the console.


Tip: More about StandardScaler class: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html


Expected result:


    [[-0.3491 -1.4385 -0.4117 -0.3905 -1.8637]
     [-0.2047  0.3126 -0.1337 -0.2759  1.0781]
     [-0.3293 -0.2151 -0.3174 -0.3644 -1.5799]
     [ 1.0274  2.0898  1.0469  0.9176  0.3163]
     [ 1.829   0.696   1.7637  1.7838 -0.3337]]
    [[-0.4681 -0.1417 -0.4447 -0.486   0.2934]
     [ 1.3645  0.4996  1.3064  1.3344 -0.3917]
     [ 0.3788  0.0665  0.4043  0.264   0.9777]
     [-0.4879 -0.3594 -0.429  -0.5256  0.7054]
     [-0.7315 -1.1261 -0.71   -0.7079  0.307 ]]




In [18]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [19]:
from google.colab import files 
uploaded = files.upload()

Saving X_test.xlsx to X_test (3).xlsx
Saving x_train.xlsx to x_train (3).xlsx


In [20]:
import io
np.set_printoptions(precision=4, suppress=True)
X_test = pd.read_excel(io.BytesIO(uploaded['X_test.xlsx']))
X_train = pd.read_excel(io.BytesIO(uploaded['x_train.xlsx']))

In [21]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [22]:
xtrain_scaled = scaler.transform(X_train)
xtest_scaled = scaler.transform(X_test)

In [23]:
print(xtrain_scaled[:5])
print(xtest_scaled[:5])

[[-0.3491 -1.4385 -0.4117 -0.3905 -1.8637]
 [-0.2047  0.3126 -0.1337 -0.2759  1.0781]
 [-0.3293 -0.2151 -0.3174 -0.3644 -1.5799]
 [ 1.0274  2.0898  1.0469  0.9176  0.3163]
 [ 1.829   0.696   1.7637  1.7838 -0.3337]]
[[-0.4681 -0.1417 -0.4447 -0.486   0.2934]
 [ 1.3645  0.4996  1.3064  1.3344 -0.3917]
 [ 0.3788  0.0665  0.4043  0.264   0.9777]
 [-0.4879 -0.3594 -0.429  -0.5256  0.7054]
 [-0.7315 -1.1261 -0.71   -0.7079  0.307 ]]
