<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/Day46.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 46

The predictions.csv file contains predictions based on the certain multi-class classification model (3 classes). The y_true column describes the actual values, and the y_pred column describes the values predicted by the model.


Use the confusion_matrix() function from the scikit-learn package to calculate the confusion matrix and print it to the console.


Tip: More about confusion_matrix() function: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html


Expected result:


    [[ 6  1  0]
     [ 3 10  2]
     [ 0  2  5]]




In [5]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

In [6]:
from google.colab import files
uploaded = files.upload()


Saving prediction.xlsx to prediction (1).xlsx


In [7]:
import io
df = pd.read_excel(io.BytesIO(uploaded['prediction.xlsx']))


In [8]:
cm = confusion_matrix(df['y_true'], df['y_pred'])
print(cm)

[[ 6  1  0]
 [ 3 10  2]
 [ 0  2  5]]
