<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/Day68.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 67

Load the pca.csv file into the df DataFrame. This file contains three explanatory variables var1, var2, var3 and the class variable. Extract the following variables: var1, var2, var3 and assign to the X variable, also extract class column and assign to the y variable.


Using the StandardScaler class, standardize X and assign to the X_std variable.

In response, print the first ten rows of the X_std array to the console.


Tip: More about StandardScaler class: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html


Expected result:


    [[-0.90068117 -1.34022653 -1.3154443 ]
     [-1.14301691 -1.34022653 -1.3154443 ]
     [-1.38535265 -1.39706395 -1.3154443 ]
     [-1.50652052 -1.2833891  -1.3154443 ]
     [-1.02184904 -1.34022653 -1.3154443 ]
     [-0.53717756 -1.16971425 -1.05217993]
     [-1.50652052 -1.34022653 -1.18381211]
     [-1.02184904 -1.2833891  -1.3154443 ]
     [-1.74885626 -1.34022653 -1.3154443 ]
     [-1.14301691 -1.2833891  -1.44707648]]

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
np.random.seed(42)

In [3]:
from google.colab import files
uploaded = files.upload()

Saving pca.csv to pca.csv


In [6]:
df = pd.read_csv('pca.csv')
df.head()

var1  var2  var3  class
0   5.1   1.4   0.2      0
1   4.9   1.4   0.2      0
2   4.7   1.3   0.2      0
3   4.6   1.5   0.2      0
4   5.0   1.4   0.2      0

In [7]:
X = df.copy()
y = X.pop('class')

In [8]:
scaler = StandardScaler()
X_std = scaler.fit_transform(X)
print(X_std[:10])

[[-0.90068117 -1.34022653 -1.3154443 ]
 [-1.14301691 -1.34022653 -1.3154443 ]
 [-1.38535265 -1.39706395 -1.3154443 ]
 [-1.50652052 -1.2833891  -1.3154443 ]
 [-1.02184904 -1.34022653 -1.3154443 ]
 [-0.53717756 -1.16971425 -1.05217993]
 [-1.50652052 -1.34022653 -1.18381211]
 [-1.02184904 -1.2833891  -1.3154443 ]
 [-1.74885626 -1.34022653 -1.3154443 ]
 [-1.14301691 -1.2833891  -1.44707648]]
