<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/math/Day38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 38

Load the data.csv file into the DataFrame.

Then extract polynomial features from var1 and var2 columns with degree = 3.

In response, print result to the console.


Tip: Use PolynomialFeatures class: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html


Expected result:


    [[  1.     -0.016   0.589   0.     -0.01    0.347  -0.      0.     -0.006   0.204]
     [  1.      0.754   0.076   0.569   0.058   0.006   0.429   0.043   0.004   0.   ]
     [  1.     -1.157  -1.465   1.338   1.695   2.146  -1.548  -1.96   -2.482  -3.143]
     [  1.      0.177  -0.175   0.031  -0.031   0.031   0.006  -0.006   0.005  -0.005]
     [  1.     -2.502   1.536   6.258  -3.843   2.36  -15.656   9.615  -5.905   3.626]
     [  1.      0.631   0.537   0.398   0.339   0.288   0.251   0.214   0.182   0.155]
     [  1.      0.239   0.227   0.057   0.054   0.051   0.014   0.013   0.012   0.012]
     [  1.      1.062   0.598   1.127   0.635   0.358   1.197   0.675   0.38    0.214]
     [  1.     -0.837  -0.328   0.7     0.275   0.108  -0.586  -0.23   -0.09   -0.035]
     [  1.      0.567  -0.313   0.321  -0.178   0.098   0.182  -0.101   0.056  -0.031]
     [  1.      0.845  -2.593   0.714  -2.191   6.726   0.603  -1.852   5.684 -17.444]
     [  1.     -0.498   0.997   0.248  -0.497   0.994  -0.124   0.247  -0.495   0.991]
     [  1.     -0.753   0.89    0.566  -0.67    0.792  -0.426   0.504  -0.596   0.704]
     [  1.      0.549  -1.034   0.302  -0.568   1.068   0.166  -0.312   0.587  -1.104]
     [  1.      0.872   0.405   0.76    0.353   0.164   0.662   0.307   0.143   0.066]
     [  1.      1.309  -1.543   1.713  -2.019   2.38    2.243  -2.643   3.115  -3.672]
     [  1.     -1.486  -0.926   2.208   1.376   0.858  -3.28   -2.045  -1.275  -0.795]
     [  1.     -0.192  -1.319   0.037   0.253   1.739  -0.007  -0.048  -0.333  -2.293]
     [  1.      0.786   0.64    0.618   0.503   0.409   0.486   0.396   0.322   0.262]
     [  1.     -0.013   0.489   0.     -0.006   0.24   -0.      0.     -0.003   0.117]
     [  1.      0.849  -1.723   0.72   -1.462   2.969   0.612  -1.241   2.52   -5.115]
     [  1.     -0.175   0.269   0.031  -0.047   0.072  -0.005   0.008  -0.013   0.019]
     [  1.      0.289   0.723   0.084   0.209   0.523   0.024   0.06    0.151   0.378]
     [  1.     -0.761  -0.848   0.579   0.646   0.72   -0.441  -0.492  -0.548  -0.61 ]
     [  1.     -0.556   0.191   0.309  -0.106   0.037  -0.172   0.059  -0.02    0.007]
     [  1.     -0.137  -1.477   0.019   0.203   2.182  -0.003  -0.028  -0.3    -3.224]
     [  1.      0.369  -0.511   0.136  -0.189   0.261   0.05   -0.07    0.096  -0.133]
     [  1.      2.415   0.031   5.833   0.074   0.001  14.087   0.179   0.002   0.   ]
     [  1.     -1.502  -1.225   2.257   1.841   1.502  -3.39   -2.766  -2.256  -1.84 ]
     [  1.      0.642   1.024   0.412   0.658   1.049   0.265   0.423   0.674   1.075]]




In [11]:
import pandas as pd

In [12]:
from google.colab import files
 
 
uploaded = files.upload()

Saving ex38.xlsx to ex38 (1).xlsx


In [13]:


import io
 
df = pd.read_excel(io.BytesIO(uploaded['ex38.xlsx']))
print(df)



        var1      var2
0  -0.016394  0.588725
1   0.754263  0.076439
2  -1.156829 -1.464842
3   0.177427 -0.174888
4  -2.501646  1.536316
5   0.630730  0.536867
6   0.238584  0.226936
7   1.061786  0.598469
8  -0.836619 -0.328465
9   0.566904 -0.313286
10  0.844989 -2.593484
11 -0.498073  0.997011
12 -0.752527  0.889785
13  0.549175 -1.033637
14  0.871661  0.404652
15  1.308952 -1.542713
16 -1.485825 -0.926320
17 -0.191548 -1.318588
18  0.786401  0.639635
19 -0.012960  0.489420
20  0.848809 -1.723002
21 -0.174934  0.269082
22  0.289112  0.723106
23 -0.761248 -0.848320
24 -0.556091  0.191200
25 -0.137356 -1.477279
26  0.369310 -0.511035
27  2.415129  0.030721
28 -1.502268 -1.225453
29  0.642227  1.024442


In [14]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures


In [15]:
np.set_printoptions(suppress=True, precision=3)
poly = PolynomialFeatures(degree=3)

In [16]:
df_poly = poly.fit_transform(df)
print(df_poly)

[[  1.     -0.016   0.589   0.     -0.01    0.347  -0.      0.     -0.006
    0.204]
 [  1.      0.754   0.076   0.569   0.058   0.006   0.429   0.043   0.004
    0.   ]
 [  1.     -1.157  -1.465   1.338   1.695   2.146  -1.548  -1.96   -2.482
   -3.143]
 [  1.      0.177  -0.175   0.031  -0.031   0.031   0.006  -0.006   0.005
   -0.005]
 [  1.     -2.502   1.536   6.258  -3.843   2.36  -15.656   9.615  -5.905
    3.626]
 [  1.      0.631   0.537   0.398   0.339   0.288   0.251   0.214   0.182
    0.155]
 [  1.      0.239   0.227   0.057   0.054   0.051   0.014   0.013   0.012
    0.012]
 [  1.      1.062   0.598   1.127   0.635   0.358   1.197   0.675   0.38
    0.214]
 [  1.     -0.837  -0.328   0.7     0.275   0.108  -0.586  -0.23   -0.09
   -0.035]
 [  1.      0.567  -0.313   0.321  -0.178   0.098   0.182  -0.101   0.056
   -0.031]
 [  1.      0.845  -2.593   0.714  -2.191   6.726   0.603  -1.852   5.684
  -17.444]
 [  1.     -0.498   0.997   0.248  -0.497   0.994  -0.124   0.247  