<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/math/Day42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 42

Load the data.csv file into the DataFrame.

Then, using the StandardScaler class from the scikit-learn package, standardize all the variables.

In response, print result to the console.


Tip: More about StandardScaler class: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html


Expected result:


    [[-0.4785 -0.2137 -0.4584 -0.5114  0.0636]
     [ 1.3742  0.3895  1.2924  1.4055 -0.616 ]
     [ 0.3777 -0.0178  0.3905  0.2783  0.7424]
     [-0.4986 -0.4185 -0.4427 -0.5531  0.4723]
     [-0.7449 -1.1397 -0.7236 -0.745   0.0771]
     [ 1.8496  2.1747  1.9719  1.8048  1.3537]
     [ 2.2534  0.5208  2.2644  2.4466  0.5363]
     [ 0.9819 -1.0039  0.9382  0.8882 -0.0203]
     [-0.2294 -0.8236 -0.236  -0.3987  0.6429]
     [-0.069  -0.6544 -0.1338 -0.1639 -2.1663]
     [-0.2666  1.2665 -0.3344 -0.3457 -0.7709]
     [ 0.7557 -0.1692  0.7035  0.6847 -0.7183]
     [ 0.2374  0.0445  0.1351  0.1047 -1.0339]
     [ 0.6068  0.5164  0.6293  0.5087  1.2613]
     [-0.5158 -1.6227 -0.5469 -0.551  -0.6202]
     [ 1.4201  1.498   1.5189  1.4114  1.6167]
     [ 0.1916 -1.0818  0.1005  0.0766 -0.9977]
     [-1.14    0.0066 -1.1321 -1.0148  0.1098]
     [-2.0504 -1.3645 -1.9945 -1.5123  1.2968]
     [ 1.8353  0.2893  1.8772  1.932   0.4154]
     [-0.0977 -0.8392 -0.0737 -0.2091  0.1382]
     [-0.5845 -0.4096 -0.5827 -0.617   0.2946]
     [ 2.1388  0.6054  2.149   2.2248  1.2755]
     [-1.1773  0.3828 -1.1956 -1.0278 -1.25  ]
     [-0.7277  1.0973 -0.7409 -0.7027 -1.7071]
     [-0.175  -1.9188 -0.1775 -0.2828  2.1569]
     [-0.2466 -1.3    -0.2648 -0.3342 -1.0752]
     [-1.1028  1.7918 -1.0934 -0.9861 -0.601 ]
     [-0.3955 -0.1603 -0.4262 -0.4679 -0.1419]
     [ 0.876   1.104   0.9053  0.8122  0.5931]
     [-0.8623  0.641  -0.8537 -0.8175 -0.22  ]
     [-0.5959 -1.5181 -0.6334 -0.6099 -0.4013]
     [-1.2597 -0.098  -1.2474 -1.0798  0.6216]
     [-0.132  -0.719  -0.1837 -0.2345 -0.4255]
     [-1.1343 -0.4519 -1.1161 -1.0106  0.5221]
     [-0.7506 -0.1803 -0.7775 -0.727  -0.2499]
     [ 0.5381  0.8191  0.4316  0.423  -1.1868]
     [-0.6876 -1.2332 -0.7405 -0.6729 -1.4661]
     [ 1.1767  0.0935  1.1277  1.1393 -0.2933]
     [ 0.1371  0.9927  0.0968  0.0234 -0.6409]
     [-1.0455 -0.0601 -1.0218 -0.9426  0.0806]
     [ 0.2689  1.3756  0.2381  0.1828  0.259 ]
     [-0.7248 -0.788  -0.6902 -0.7294  0.714 ]
     [-0.6589 -0.138  -0.6882 -0.6708 -0.7141]
     [-0.6446 -0.4897 -0.6597 -0.6483  1.6878]
     [-0.8021  0.3784 -0.813  -0.764  -0.7937]
     [-1.3877 -1.2599 -1.3286 -1.1742  2.7256]
     [-1.3511  1.8519 -1.3574 -1.1343 -1.2458]
     [-0.7076  0.1024 -0.7005 -0.7057  0.2022]
     [-0.3583 -0.8592 -0.3352 -0.4087 -1.4626]
     [ 0.8731  0.5587  0.7982  0.8089 -0.1063]
     [ 1.2855  1.2353  1.3418  1.2813  0.5434]
     [-0.2953  0.6633 -0.2141 -0.3709  0.1027]
     [-0.0576 -1.4224 -0.0786 -0.1792  1.8513]
     [-0.6418 -1.0929 -0.5811 -0.6566  1.1689]
     [-0.2781 -0.2983 -0.327  -0.3475 -1.7128]
     [-1.1143 -0.7524 -1.0584 -0.9778  0.5221]
     [ 3.1726  1.1908  3.2651  3.6178  0.5363]
     [-0.1893  0.2804 -0.1573 -0.2828  0.2022]
     [-0.8164 -1.4513 -0.8232 -0.7891 -0.0295]
     [-0.3669 -0.3473 -0.3719 -0.4392  0.0415]
     [ 1.589   0.3761  1.556   1.6214  0.7708]
     [ 2.1245  0.6299  2.0502  2.4377  0.8704]
     [ 0.0741  1.6538  0.0013 -0.0257 -2.0476]
     [-0.5272 -0.1202 -0.5906 -0.5631 -1.1107]
     [-0.4356  0.9816 -0.4476 -0.4685 -1.4021]
     [ 0.4693  0.7456  0.5552  0.378   1.1902]
     [ 1.7293  0.9816  2.1202  1.7456  2.1214]
     [-0.6675 -0.483  -0.698  -0.6681  0.1382]
     [-0.3325 -0.0468 -0.3171 -0.4164 -0.2108]
     [-0.1063  0.6076 -0.0655 -0.1949  1.5101]
     [ 0.4693 -0.3718  0.4687  0.3733 -0.1177]
     [-0.0232 -0.5298 -0.1017 -0.1352 -1.3012]
     [ 0.6641  0.1224  0.7035  0.5268 -0.0317]
     [-1.8362  1.3199 -1.822  -1.4079 -1.2635]
     [-0.1922 -1.2243 -0.2018 -0.3209  0.5931]
     [-0.0318  0.3761 -0.1    -0.152  -0.5726]
     [-0.0519 -0.5587 -0.0325 -0.155   0.7708]
     [-0.9711 -1.0217 -0.9868 -0.8858 -1.4803]
     [-0.8222 -1.4691 -0.7849 -0.7941  1.7731]
     [ 0.5781  0.4407  0.5758  0.4584  0.1453]
     [-0.8279 -1.064  -0.8583 -0.7832 -1.1157]
     [ 0.0971  0.4229  0.0836 -0.0195 -0.3068]
     [ 1.947   0.8903  1.9225  2.0976  0.1382]
     [ 1.085   1.0951  0.9464  1.0177 -0.7254]
     [ 0.3376 -0.5098  0.4522  0.173   2.4697]
     [-0.4814  0.9972 -0.3397 -0.5291  1.4106]
     [ 0.9905  0.8391  1.1029  0.9633 -0.4169]
     [-0.5988  0.7034 -0.5547 -0.6122 -2.0902]
     [-0.3669 -1.389  -0.3871 -0.4436  1.041 ]
     [-0.6131 -0.8704 -0.6289 -0.6255 -0.1084]
     [-0.195  -0.1803 -0.1968 -0.3067  0.6216]
     [ 0.2574 -0.6277  0.2681  0.1023  0.0053]
     [-0.8422  2.1836 -0.8875 -0.795  -1.7249]
     [-0.8365  0.0667 -0.8352 -0.7912  0.4723]
     [-1.2497 -0.5721 -1.224  -1.0784  0.3515]
     [ 1.715   1.9343  1.6054  1.793  -0.0679]
     [-0.0948  0.9326 -0.0272 -0.1686  2.3844]
     [-0.8565 -1.4424 -0.8793 -0.8071 -0.0864]
     [ 0.896   1.3043  0.8311  0.8104 -1.0979]
     [ 0.4464  0.1669  0.3699  0.3307 -0.198 ]
     [-1.2609 -1.6895 -1.2759 -1.0834 -0.4447]
     [ 1.1194 -0.7591  1.1524  1.0387  0.5505]
     [ 1.1022  0.2448  1.0535  0.9964  0.3443]
     [-0.951   1.035  -0.9608 -0.8672 -1.1967]
     [-0.6847 -0.4452 -0.6725 -0.6859  0.6073]
     [-0.5158  0.5921 -0.5094 -0.5628  0.1737]
     [ 2.5627  0.0601  2.4662  3.0381 -0.3793]
     [ 0.0856 -0.975   0.0721 -0.0435  0.0671]
     [ 0.1429 -0.6032  0.082   0.0331 -0.8776]
     [ 0.5524  0.02    0.4893  0.4818 -0.503 ]
     [-0.7506 -1.0306 -0.7557 -0.735   0.1809]
     [ 0.0226  1.8452  0.0136 -0.0914 -1.1747]
     [ 1.8868  2.5731  1.7907  2.2603 -0.289 ]
     [-1.4639 -0.4964 -1.3768 -1.1958  0.5576]
     [ 1.9899  1.5603  2.079   1.9408  1.0907]
     [-1.4227 -1.2688 -1.3599 -1.165  -1.5315]
     [-0.9997  1.2598 -0.997  -0.9104 -0.1554]
     [-1.1372 -1.0417 -1.1395 -1.0142  1.041 ]
     [ 0.1142  1.7762  0.1858  0.0118  1.0765]
     [ 0.077   0.0378  0.1569 -0.0112 -0.7951]
     [-0.7764 -0.9282 -0.7891 -0.7542 -0.1682]
     [-0.5415 -0.3606 -0.5745 -0.5753 -0.8683]
     [ 1.6463  0.1558  1.5766  1.6539  0.3515]
     [-0.51    0.4986 -0.5123 -0.5581 -0.7844]
     [ 1.9928  0.2137  1.8896  2.1567 -0.1362]
     [ 0.2087 -0.6433  0.2644  0.0819  1.24  ]
     [-1.2812 -0.2382 -1.2656 -1.0816 -0.6608]
     [-0.2122 -0.581  -0.2776 -0.3029 -1.378 ]
     [ 1.4687  1.5381  1.4695  1.5001 -0.3373]
     [ 1.1022 -2.0434  1.2595  1.024   1.3964]
     [ 0.309   2.4618  0.4605  0.1837  0.4296]
     [ 0.0341 -0.3094 -0.0412 -0.0642 -2.3454]
     [-0.699  -0.1002 -0.7368 -0.6983 -0.7546]
     [ 0.3233 -1.4802  0.2451  0.2091 -1.2038]
     [ 0.3433 -1.1798  0.4234  0.1467  0.6073]
     [-0.1807 -0.1492 -0.1697 -0.286   0.5078]
     [-1.0484  0.0667 -1.0502 -0.9379  0.586 ]
     [ 0.1429 -0.9616  0.1462 -0.0086  1.0267]
     [ 0.0885  0.1469  0.0935 -0.0358 -0.0025]
     [-0.888  -0.6077 -0.8772 -0.8329  0.6358]
     [ 1.6234  0.5765  1.556   1.79   -0.0317]
     [-1.1114 -1.6338 -1.0901 -0.9855  0.0856]]


Line 1, Column 1
All changes saved


In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


In [13]:

from google.colab import files
 
 
uploaded = files.upload()

Saving ex42.xlsx to ex42 (1).xlsx


In [14]:

import io
 
df = pd.read_excel(io.BytesIO(uploaded['ex42.xlsx']))
print(df)

      var1   var2    var3    var4     var5
0    12.47  18.60   81.09   481.9  0.09965
1    18.94  21.31  123.60  1130.0  0.09009
2    15.46  19.48  101.70   748.9  0.10920
3    12.40  17.68   81.47   467.8  0.10540
4    11.54  14.44   74.65   402.9  0.09984
..     ...    ...     ...     ...      ...
138  14.64  15.24   95.77   651.9  0.11320
139  14.45  20.22   94.49   642.7  0.09872
140  11.04  16.83   70.92   373.2  0.10770
141  19.81  22.15  130.00  1260.0  0.09831
142  10.26  12.22   65.75   321.6  0.09996

[143 rows x 5 columns]


In [15]:

np.set_printoptions(precision = 4 , suppress = True)


In [16]:
scaler = StandardScaler()
print(scaler.fit(df))


StandardScaler()


In [17]:
df_scaled = scaler.transform(df)
print(df_scaled)

[[-0.4785 -0.2137 -0.4584 -0.5114  0.0636]
 [ 1.3742  0.3895  1.2924  1.4055 -0.616 ]
 [ 0.3777 -0.0178  0.3905  0.2783  0.7424]
 [-0.4986 -0.4185 -0.4427 -0.5531  0.4723]
 [-0.7449 -1.1397 -0.7236 -0.745   0.0771]
 [ 1.8496  2.1747  1.9719  1.8048  1.3537]
 [ 2.2534  0.5208  2.2644  2.4466  0.5363]
 [ 0.9819 -1.0039  0.9382  0.8882 -0.0203]
 [-0.2294 -0.8236 -0.236  -0.3987  0.6429]
 [-0.069  -0.6544 -0.1338 -0.1639 -2.1663]
 [-0.2666  1.2665 -0.3344 -0.3457 -0.7709]
 [ 0.7557 -0.1692  0.7035  0.6847 -0.7183]
 [ 0.2374  0.0445  0.1351  0.1047 -1.0339]
 [ 0.6068  0.5164  0.6293  0.5087  1.2613]
 [-0.5158 -1.6227 -0.5469 -0.551  -0.6202]
 [ 1.4201  1.498   1.5189  1.4114  1.6167]
 [ 0.1916 -1.0818  0.1005  0.0766 -0.9977]
 [-1.14    0.0066 -1.1321 -1.0148  0.1098]
 [-2.0504 -1.3645 -1.9945 -1.5123  1.2968]
 [ 1.8353  0.2893  1.8772  1.932   0.4154]
 [-0.0977 -0.8392 -0.0737 -0.2091  0.1382]
 [-0.5845 -0.4096 -0.5827 -0.617   0.2946]
 [ 2.1388  0.6054  2.149   2.2248  1.2755]
 [-1.1773  