<a href="https://colab.research.google.com/github/chaugaialberteinstein/112_days_code_challenge/blob/main/Day_37.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 37 : [Polynomial Feature Transform]

Load the data.csv file into the DataFrame.

Then extract the polynomial features from the var1 column with degree = 2.

In response, print result to the console.


Tip: Use PolynomialFeatures class: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html


Expected result:


    [[ 1.    -0.542  0.294]
     [ 1.     0.529  0.279]
     [ 1.     0.625  0.391]
     [ 1.     0.194  0.038]
     [ 1.    -0.8    0.64 ]
     [ 1.    -0.304  0.092]
     [ 1.     1.086  1.18 ]
     [ 1.    -1.16   1.346]
     [ 1.     1.038  1.078]
     [ 1.    -0.815  0.665]
     [ 1.     0.416  0.173]
     [ 1.     1.297  1.683]
     [ 1.    -0.433  0.187]
     [ 1.     1.059  1.121]
     [ 1.     1.139  1.297]
     [ 1.     1.     1.   ]
     [ 1.     0.109  0.012]
     [ 1.    -0.39   0.152]
     [ 1.    -0.701  0.491]
     [ 1.     0.698  0.488]
     [ 1.     0.752  0.565]
     [ 1.     0.661  0.437]
     [ 1.    -0.964  0.93 ]
     [ 1.    -0.252  0.064]
     [ 1.     0.344  0.119]
     [ 1.     0.524  0.274]
     [ 1.    -0.164  0.027]
     [ 1.     0.048  0.002]
     [ 1.     0.606  0.367]
     [ 1.    -0.148  0.022]]




In [6]:
import pandas as pd


In [7]:
from google.colab import files
 
 
uploaded = files.upload()

Saving ex37.xlsx to ex37.xlsx


In [8]:
import io
 
df = pd.read_excel(io.BytesIO(uploaded['ex37.xlsx']))
print(df)



        var1
0  -0.542034
1   0.528620
2   0.625143
3   0.193978
4  -0.800259
5  -0.303532
6   1.086180
7  -1.160182
8   1.038314
9  -0.815303
10  0.416017
11  1.297113
12 -0.432866
13  1.058744
14  1.138776
15  0.999913
16  0.108967
17 -0.390140
18 -0.700645
19  0.698312
20  0.751571
21  0.661245
22 -0.964250
23 -0.252193
24  0.344255
25  0.523882
26 -0.163831
27  0.048342
28  0.605599
29 -0.148273


In [9]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

In [10]:
np.set_printoptions(suppress=True, precision=3)


In [11]:
poly = PolynomialFeatures(degree=2)
     
df_poly = poly.fit_transform(df)
print(df_poly)

[[ 1.    -0.542  0.294]
 [ 1.     0.529  0.279]
 [ 1.     0.625  0.391]
 [ 1.     0.194  0.038]
 [ 1.    -0.8    0.64 ]
 [ 1.    -0.304  0.092]
 [ 1.     1.086  1.18 ]
 [ 1.    -1.16   1.346]
 [ 1.     1.038  1.078]
 [ 1.    -0.815  0.665]
 [ 1.     0.416  0.173]
 [ 1.     1.297  1.683]
 [ 1.    -0.433  0.187]
 [ 1.     1.059  1.121]
 [ 1.     1.139  1.297]
 [ 1.     1.     1.   ]
 [ 1.     0.109  0.012]
 [ 1.    -0.39   0.152]
 [ 1.    -0.701  0.491]
 [ 1.     0.698  0.488]
 [ 1.     0.752  0.565]
 [ 1.     0.661  0.437]
 [ 1.    -0.964  0.93 ]
 [ 1.    -0.252  0.064]
 [ 1.     0.344  0.119]
 [ 1.     0.524  0.274]
 [ 1.    -0.164  0.027]
 [ 1.     0.048  0.002]
 [ 1.     0.606  0.367]
 [ 1.    -0.148  0.022]]
